import {
  adminAndOwnerOnly,
  adminOwnerAndStaffOnly,
  superAdminAndAdminOnly,
  superAdminOnly,
  superAdminAndAdminAndBrandOnly,
} from '@utils/auth-utils';
import { ROUTES } from '@utils/routes';

export const siteSettings = {
  name: 'Lexir',
  description: '',
  logo: {
    url: '/logo.svg',
    alt: 'Lexir',
    href: '/',
    width: 96,
    height: 32,
  },
  defaultLanguage: 'en',
  author: {
    name: '',
    websiteUrl: '',
    address: '',
  },
  headerLinks: [],
  authorizedLinks: [
    // {
    //     href: ROUTES.PROFILE_UPDATE,
    //     labelTransKey: 'authorized-nav-item-profile',
    // },
    {
      href: ROUTES.LOGOUT,
      labelTransKey: 'LOGOUT',
    },
  ],
  currencyCode: 'USD',
  sidebarLinks: {
    admin: [
      // {
      //   href: ROUTES.SITES,
      //   label: "SITES",
      //   icon: "CategoriesIcon",
      //   permissions: superAdminOnly,
      // },
      {
        href: ROUTES.DASHBOARD,
        label: 'Dashboard',
        icon: 'DashboardIcon',
        iconActivated: 'DashboardIconActivated',
        permissions: superAdminAndAdminAndBrandOnly,
      },
      {
        href: ROUTES.ORDERS,
        label: 'Orders',
        icon: 'OrdersIcon',
        iconActivated: 'OrdersIconActivated',
        permissions: superAdminAndAdminAndBrandOnly,
      },
      {
        href: ROUTES.BRANDS,
        label: 'Brands',
        icon: 'TagIcon',
        iconActivated: 'TagIconActivated',
        permissions: superAdminOnly,
      },
      {
        href: ROUTES.CUSTOMERS,
        label: 'Customers',
        icon: 'UsersIcon',
        iconActivated: 'UsersIconActivated',
        permissions: superAdminAndAdminAndBrandOnly,
      },
      {
        href: ROUTES.STOCKS,
        label: 'Stock',
        icon: 'StockIcon',
        iconActivated: 'StockIconActivated',
        permissions: superAdminAndAdminAndBrandOnly,
      },
      {
        href: ROUTES.PRODUCTS,
        label: 'Products',
        icon: 'ProductsIcon',
        iconActivated: 'ProductsIconActivated',
        permissions: superAdminAndAdminAndBrandOnly,
      },
      {
        href: ROUTES.INTEGRATIONS,
        label: 'Integrations',
        icon: 'PlugIcon',
        iconActivated: 'PlugIconActivated',
        permissions: superAdminOnly,
      },
      {
        href: ROUTES.ONBOARDINGBRANDS,
        label: 'Brands Onboarding',
        icon: 'PlugIcon',
        iconActivated: 'PlugIconActivated',
        permissions: superAdminOnly,
      },
      // {
      //   href: ROUTES.WITHDRAWS,
      //   label: "Payouts",
      //   icon: "WithdrawIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.SETTINGS,
      //   label: "Settings",
      //   icon: "SettingsIcon",
      //   permissions: superAdminOnly,
      // },
      // {
      //   href: ROUTES.CATEGORIES,
      //   label: "sidebar-nav-item-categories",
      //   icon: "CategoriesIcon",
      //   permissions: superAdminOnly,
      // },
      // {
      //   href: ROUTES.SHOPS,
      //   label: "sidebar-nav-item-shops",
      //   icon: "ShopIcon",
      //   permissions: superAdminOnly,
      // },
      // {
      //   href: ROUTES.ADMIN_MY_SHOPS,
      //   label: "sidebar-nav-item-my-shops",
      //   icon: "MyShopIcon",
      //   permissions: [superAdminOnly, adminOnly],
      // },
      // {
      //   href: ROUTES.ATTRIBUTES,
      //   label: "sidebar-nav-item-attributes",
      //   icon: "AttributeIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.GROUPS,
      //   label: "sidebar-nav-item-groups",
      //   icon: "TypesIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.TAGS,
      //   label: "sidebar-nav-item-tags",
      //   icon: "TagIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.MANUFACTURERS,
      //   label: "sidebar-nav-item-manufacturers",
      //   icon: "DiaryIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.AUTHORS,
      //   label: "sidebar-nav-item-authors",
      //   icon: "FountainPenIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.ORDERS,
      //   label: "sidebar-nav-item-orders",
      //   icon: "OrdersIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.ORDER_STATUS,
      //   label: "sidebar-nav-item-order-status",
      //   icon: "OrdersStatusIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.CREATE_ORDER,
      //   label: "sidebar-nav-item-create-order",
      //   icon: "CalendarScheduleIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.USERS,
      //   label: "sidebar-nav-item-users",
      //   icon: "UsersIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.COUPONS,
      //   label: "sidebar-nav-item-coupons",
      //   icon: "CouponsIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.TAXES,
      //   label: "sidebar-nav-item-taxes",
      //   icon: "TaxesIcon",
      //   permissions: adminOnly,
      // },
      // {
      //   href: ROUTES.SHIPPINGS,
      //   label: "sidebar-nav-item-shippings",
      //   icon: "ShippingsIcon",
      //   permissions: adminOnly,
      // },

      // {
      //   href: ROUTES.REFUNDS,
      //   label: "sidebar-nav-item-refunds",
      //   icon: "RefundsIcon",
      //   permissions: adminOnly,
      // },
    ],
    shop: [
      {
        href: (shop: string) => `${ROUTES.DASHBOARD}${shop}`,
        label: 'sidebar-nav-item-dashboard',
        icon: 'DashboardIcon',
        permissions: adminOwnerAndStaffOnly,
      },
      // {
      // 	href: (shop: string) => `/${shop}${ROUTES.ATTRIBUTES}`,
      // 	label: "sidebar-nav-item-attributes",
      // 	icon: "AttributeIcon",
      // 	permissions: adminOwnerAndStaffOnly,
      // },
      {
        href: (shop: string) => `/${shop}${ROUTES.PRODUCTS}`,
        label: 'sidebar-nav-item-products',
        icon: 'ProductsIcon',
        permissions: adminOwnerAndStaffOnly,
      },
      // {
      //   href: (shop: string) => `/${shop}${ROUTES.AUTHORS}`,
      //   label: "sidebar-nav-item-authors",
      //   icon: "FountainPenIcon",
      //   permissions: adminAndOwnerOnly,
      // },
      // {
      //   href: (shop: string) => `/${shop}${ROUTES.MANUFACTURERS}`,
      //   label: "sidebar-nav-item-manufacturers",
      //   icon: "DiaryIcon",
      //   permissions: adminAndOwnerOnly,
      // },
      {
        href: (shop: string) => `/${shop}${ROUTES.ORDERS}`,
        label: 'sidebar-nav-item-orders',
        icon: 'OrdersIcon',
        permissions: adminOwnerAndStaffOnly,
      },
      // {
      // 	href: (shop: string) => `/${shop}${ROUTES.REFUNDS}`,
      // 	label: "sidebar-nav-item-refunds",
      // 	icon: "RefundsIcon",
      // 	permissions: adminOwnerAndStaffOnly,
      // },
      {
        href: (shop: string) => `/${shop}${ROUTES.STAFFS}`,
        label: 'sidebar-nav-item-staffs',
        icon: 'UsersIcon',
        permissions: adminAndOwnerOnly,
      },
      {
        href: (shop: string) => `/${shop}${ROUTES.WITHDRAWS}`,
        label: 'sidebar-nav-item-withdraws',
        icon: 'AttributeIcon',
        permissions: adminAndOwnerOnly,
      },
    ],
  },
  product: {
    placeholder: '/product-placeholder.svg',
  },
  avatar: {
    placeholder: '/avatar-placeholder.svg',
  },
};
